bcl_destinations_linux:
  - dest: "/etc/ansible/pavel"
    type: "hard"
    src:
      - "/etc/ansible/test_1"
  - dest: "/etc/ansible/pavel1"
    src:
      - "/etc/ansible/test_1"
      - "/etc/ansible/test_2"
  - dest: "/etc/ansible/pavel2"
    type: "soft"
    src:
      - "/etc/ansible/test_2"
  - dest: "/etc/ansible/pavel3"
    type: "soft"
    src:
      - "/etc/ansible/test_1" 
